### ISSUE TITLE
collection branches to migrate to new templates

### ISSUE THREAD

**Issue by evanwill** [uidaholib/collectionbuilder-csv-template#8]
- [x] 1918flu
- [x] ames
- [x] bach-festival
- [x] blot
- [x] bpf
- [x] camasrailroad
- [x] campusart
- [x] cheatham
- [x] coursecatalogs
- [x] craigmountain
- [x] dodson
- [x] ella-fitzgerald
- [x] ernieday
- [x] fiddlers
- [x] flora
- [x] gemphotos
- [x] hiroshima
- [x] hohp
- [x] iwi
- [x] lrcdp
- [x] mcclure
- [x] raney
- [x] scrapbooks
- [x] shitamae
- [x] stockcerts
- [x] tabor
- [x] theatre
- [x] tpa
- [x] wim
- [x] winr

see "csv-template" tab of "CONTENTdm Migration Lists" sheet.

**Comment by evanwill** [comment]
@kxuidaho and @aweymo-ui  this migration is much simpler than from CDM. All configs and files are compatible.
However, do not directly copy "_config.yml" or "theme.yml" over, as there are bits that are different in the new version. 

In "_config.yml", copy over baseurl, title, tagline, description, keywords, author, and metadata only! Don't replace the other keys in the new version. 
In "theme.yml", copy over values that are customized, however, there are a few new things in the new templates, so don't just replace the full file. 

Transferring basic customizations should be pretty easy. The includes are the same as in the new template. However, old version is using older bootstrap--so if you are moving things that have bootstrap classes, there could be issues to update.

**Comment by evanwill** [comment]
Also, remember to swap out the object location URLs!
Replace `https://www.lib.uidaho.edu/digital/objects/`
with `https://objects.lib.uidaho.edu/`

**Comment by evanwill** [comment]
Also, remember to **not** transfer over old color scheme (unless it is custom specific to the collection). 
For example, 
Old home page: `{% include index/featured-terms.html field="guest_scholar" title="Guests" btn-color="info" %}`
New home page: `{% include index/featured-terms.html field="guest_scholar" title="Guests" btn-color="payette-blue" %}`
(i.e. same include customization, except new default color scheme)

**Comment by evanwill** [comment]
One last note: if you find images (like featured images or about page) in the "assets" folder of the branch, move those to libobjects server instead and update the link.

**Comment by aweymo-ui** [comment]
@kxuidaho wrapped these up yesterday --

**Comment by evanwill** [comment]
thanks @aweymo-ui and @kxuidaho !
